### ISSUE TITLE
Moto edge x30 （Android 12）测不到帧率

### ISSUE THREAD

**Issue by pacoz7** [taptap/perf-doctor#3]
其他手机测试可以正常记录数据，导出excel也正常。
Moto edge x30 不能在performance板块监测帧率曲线，其他多个测试项目可以正常显示曲线。
导出数据后，excel数据表格没有任何数据。
Android Version: 12
Current software version: MYUI S0SC32

**Comment by vinjn** [comment]
新版本已 Fix
